### ISSUE TITLE
Clarify label sync behavior

### ISSUE THREAD

**Issue by br3ndonland** [micnncim/action-label-syncer#44]
Thanks for this action, it's really helpful.

It would be helpful to clarify the behavior of the action. Based on using the action and reading [github.go](https://github.com/micnncim/action-label-syncer/blob/master/pkg/github/github.go), it appears to be doing the following:

- If a label color changes, the same label is updated with the new color
- If a label name changes, the previous label is deleted. All issues and PRs that were previously labeled with this label are now unlabeled.

Is this correct?

I'm happy to submit a PR to update the README with this info.

**Comment by displague** [comment]
I would also like to see this behavior documented. 

It's not clear to me if the repository using a source repo as a reference will remove any custom labels that are not included in that repository.

It's not clear to me if the reference file is only sourced from the specified repository or if a local copy of that file could be used to append labels to the list.

**Comment by micnncim** [comment]
Sorry for the late reply 🙇‍♂️

> * If a label color changes, the same label is updated with the new color
> * If a label name changes, the previous label is deleted. All issues and PRs that were previously labeled with this label are now unlabeled.

Your assumption is correct! So please be careful if you try to change label names.
