### ISSUE TITLE
Multiple Repositories to Apply Labels To

### ISSUE THREAD

**Issue by jneilliii** [micnncim/action-label-syncer#45]
Through experimentation I have gotten the label sync to work with applying labels to a destination repo from a central repository. Is it possible to use multiple repositories as input to sync labels across multiple repositories at once?

**Comment by micnncim** [comment]
Thank you for your feedback. I will consider introducing that.

**Comment by jneilliii** [comment]
I think I may have found a solution to this using a matrix strategy. An example of action can be found here.

https://github.com/jneilliii/github_management/blob/main/.github/workflows/label-sync.yml
