### ISSUE TITLE
Don't delete unmanaged labels

### ISSUE THREAD

**Issue by slawekjaranowski** [micnncim/action-label-syncer#47]
In some cases it will be appreciated to don't remove unmanaged labels.

eg. dependabot adds some label to manage dependencies - I want leave untouched such labels.

In current situation I must managed labels added by other tools.

So option for this case will be good.

**Comment by micnncim** [comment]
I recommend you should manage your all labels in a manifest. We can export the all existing labels by https://github.com/micnncim/label-exporter as described in README.md.

Also, about your example, Dependabot supports configuration of labels (https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#label). Many of other tools which puts labels would also support it.

**Comment by slawekjaranowski** [comment]
Imagine another case, in my organization I have repository with java code with labels 'dependencies' and 'java' and another repository with javascript so I have labels 'dependencies' and 'javascript' ... so not all repsitories have the same sets labels.

But I want to have some labels to be common for all repository in my organization.

**Comment by micnncim** [comment]
Okay, your idea would make sense. I will review your PR later. Thank you for your contribution 🙂
