### ISSUE TITLE
Sync labels from organization settings

### ISSUE THREAD

**Issue by DAmNRelentless** [micnncim/action-label-syncer#53]
Hello!

This GitHub action looks really good and very handy.
I would like to ask if it would be possible to implement that all repositories sync the labels from your organization.

In the GitHub organization settings, there is an option called `Repository defaults` where you can specify default labels.
Sadly, they are only applied on newly created repositories so if you create a new label there, you would have to add this label for each existing repository manually which is really annoying.

Do you think it's possible to add a way to sync the repository labels on all existing organization repos?

**Comment by micnncim** [comment]
Sorry for the late reply 🙇‍♂️ 

Currently, I don't have a plan to support that. https://github.com/b4b4r07/github-labeler#run-as-github-actions may satisfy your request.

**Comment by DAmNRelentless** [comment]
Alright, thanks for the answer :)
